-- phpMyAdmin SQL Dump
-- version 2.10.2
-- http://www.phpmyadmin.net
--
-- Host: localhost
-- Generation Time: Jan 13, 2009 at 02:07 PM
-- Server version: 5.0.41
-- PHP Version: 5.2.5

SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";

--
-- Database: `sample`
--

--
-- Dumping data for table `%%PREFIX%%brands`
--

INSERT INTO `%%PREFIX%%brands` (`brandid`, `brandname`, `brandpagetitle`, `brandmetakeywords`, `brandmetadesc`, `brandimagefile`) VALUES (1, 'Teste 01', '', '', '', '');
INSERT INTO `%%PREFIX%%brands` (`brandid`, `brandname`, `brandpagetitle`, `brandmetakeywords`, `brandmetadesc`, `brandimagefile`) VALUES (2, 'Teste 02', '', '', '', '');
INSERT INTO `%%PREFIX%%brands` (`brandid`, `brandname`, `brandpagetitle`, `brandmetakeywords`, `brandmetadesc`, `brandimagefile`) VALUES (3, 'Teste 03', '', NULL, NULL, '');
INSERT INTO `%%PREFIX%%brands` (`brandid`, `brandname`, `brandpagetitle`, `brandmetakeywords`, `brandmetadesc`, `brandimagefile`) VALUES (4, 'Teste 04', '', NULL, NULL, '');




INSERT INTO `%%PREFIX%%categories` (`categoryid`, `catparentid`, `catname`, `catdesc`, `catviews`, `catsort`, `catpagetitle`, `catmetakeywords`, `catmetadesc`, `catlayoutfile`, `catparentlist`, `catimagefile`, `catvisible`) VALUES (1, 0, 'Macs Brasil', '', 0, 0, '', '', '', 'category.html', '1', '', 1);
INSERT INTO `%%PREFIX%%categories` (`categoryid`, `catparentid`, `catname`, `catdesc`, `catviews`, `catsort`, `catpagetitle`, `catmetakeywords`, `catmetadesc`, `catlayoutfile`, `catparentlist`, `catimagefile`, `catvisible`) VALUES (2, 0, 'iPhones Brasil', '', 0, 0, '', '', '', 'category.html', '2', '', 1);
INSERT INTO `%%PREFIX%%categories` (`categoryid`, `catparentid`, `catname`, `catdesc`, `catviews`, `catsort`, `catpagetitle`, `catmetakeywords`, `catmetadesc`, `catlayoutfile`, `catparentlist`, `catimagefile`, `catvisible`) VALUES (3, 0, 'Mp3 e Mp4', '', 0, 0, '', '', '', 'category.html', '3', '', 1);
INSERT INTO `%%PREFIX%%categories` (`categoryid`, `catparentid`, `catname`, `catdesc`, `catviews`, `catsort`, `catpagetitle`, `catmetakeywords`, `catmetadesc`, `catlayoutfile`, `catparentlist`, `catimagefile`, `catvisible`) VALUES (4, 1, 'Acessorios', '', 0, 0, '', '', '', 'category.html', '1,4', '', 1);
INSERT INTO `%%PREFIX%%categories` (`categoryid`, `catparentid`, `catname`, `catdesc`, `catviews`, `catsort`, `catpagetitle`, `catmetakeywords`, `catmetadesc`, `catlayoutfile`, `catparentlist`, `catimagefile`, `catvisible`) VALUES (5, 1, 'Notebooks e PCs', '', 0, 0, '', '', '', 'category.html', '1,5', '', 1);
INSERT INTO `%%PREFIX%%categories` (`categoryid`, `catparentid`, `catname`, `catdesc`, `catviews`, `catsort`, `catpagetitle`, `catmetakeywords`, `catmetadesc`, `catlayoutfile`, `catparentlist`, `catimagefile`, `catvisible`) VALUES (6, 1, 'Videos e Cameras', '', 0, 0, '', '', '', 'category.html', '1,6', '', 1);
INSERT INTO `%%PREFIX%%categories` (`categoryid`, `catparentid`, `catname`, `catdesc`, `catviews`, `catsort`, `catpagetitle`, `catmetakeywords`, `catmetadesc`, `catlayoutfile`, `catparentlist`, `catimagefile`, `catvisible`) VALUES (7, 2, 'Acessorios', '', 0, 0, '', '', '', 'category.html', '2,7', '', 1);
INSERT INTO `%%PREFIX%%categories` (`categoryid`, `catparentid`, `catname`, `catdesc`, `catviews`, `catsort`, `catpagetitle`, `catmetakeywords`, `catmetadesc`, `catlayoutfile`, `catparentlist`, `catimagefile`, `catvisible`) VALUES (8, 3, 'Acessorios', '', 0, 0, '', '', '', 'category.html', '3,8', '', 1);
INSERT INTO `%%PREFIX%%categories` (`categoryid`, `catparentid`, `catname`, `catdesc`, `catviews`, `catsort`, `catpagetitle`, `catmetakeywords`, `catmetadesc`, `catlayoutfile`, `catparentlist`, `catimagefile`, `catvisible`) VALUES (9, 1, 'Programas', '<br/>', 0, 0, '', '', '', 'category.html', '1,9', '', 1);


INSERT INTO `%%PREFIX%%categoryassociations` (`associationid`, `productid`, `categoryid`) VALUES (86, 1, 3);
INSERT INTO `%%PREFIX%%categoryassociations` (`associationid`, `productid`, `categoryid`) VALUES (87, 2, 3);
INSERT INTO `%%PREFIX%%categoryassociations` (`associationid`, `productid`, `categoryid`) VALUES (83, 3, 3);
INSERT INTO `%%PREFIX%%categoryassociations` (`associationid`, `productid`, `categoryid`) VALUES (81, 4, 3);
INSERT INTO `%%PREFIX%%categoryassociations` (`associationid`, `productid`, `categoryid`) VALUES (80, 5, 1);
INSERT INTO `%%PREFIX%%categoryassociations` (`associationid`, `productid`, `categoryid`) VALUES (79, 6, 1);
INSERT INTO `%%PREFIX%%categoryassociations` (`associationid`, `productid`, `categoryid`) VALUES (78, 7, 1);
INSERT INTO `%%PREFIX%%categoryassociations` (`associationid`, `productid`, `categoryid`) VALUES (77, 8, 6);
INSERT INTO `%%PREFIX%%categoryassociations` (`associationid`, `productid`, `categoryid`) VALUES (76, 9, 6);
INSERT INTO `%%PREFIX%%categoryassociations` (`associationid`, `productid`, `categoryid`) VALUES (75, 10, 9);
INSERT INTO `%%PREFIX%%categoryassociations` (`associationid`, `productid`, `categoryid`) VALUES (74, 11, 9);
INSERT INTO `%%PREFIX%%categoryassociations` (`associationid`, `productid`, `categoryid`) VALUES (73, 12, 9);
INSERT INTO `%%PREFIX%%categoryassociations` (`associationid`, `productid`, `categoryid`) VALUES (72, 13, 9);
INSERT INTO `%%PREFIX%%categoryassociations` (`associationid`, `productid`, `categoryid`) VALUES (71, 14, 4);
INSERT INTO `%%PREFIX%%categoryassociations` (`associationid`, `productid`, `categoryid`) VALUES (70, 15, 4);
INSERT INTO `%%PREFIX%%categoryassociations` (`associationid`, `productid`, `categoryid`) VALUES (69, 16, 4);
INSERT INTO `%%PREFIX%%categoryassociations` (`associationid`, `productid`, `categoryid`) VALUES (89, 17, 4);
INSERT INTO `%%PREFIX%%categoryassociations` (`associationid`, `productid`, `categoryid`) VALUES (68, 18, 5);
INSERT INTO `%%PREFIX%%categoryassociations` (`associationid`, `productid`, `categoryid`) VALUES (67, 19, 5);
INSERT INTO `%%PREFIX%%categoryassociations` (`associationid`, `productid`, `categoryid`) VALUES (66, 20, 5);
INSERT INTO `%%PREFIX%%categoryassociations` (`associationid`, `productid`, `categoryid`) VALUES (65, 21, 5);
INSERT INTO `%%PREFIX%%categoryassociations` (`associationid`, `productid`, `categoryid`) VALUES (63, 22, 7);
INSERT INTO `%%PREFIX%%categoryassociations` (`associationid`, `productid`, `categoryid`) VALUES (64, 22, 8);
INSERT INTO `%%PREFIX%%categoryassociations` (`associationid`, `productid`, `categoryid`) VALUES (59, 23, 7);
INSERT INTO `%%PREFIX%%categoryassociations` (`associationid`, `productid`, `categoryid`) VALUES (60, 23, 8);
INSERT INTO `%%PREFIX%%categoryassociations` (`associationid`, `productid`, `categoryid`) VALUES (58, 24, 8);
INSERT INTO `%%PREFIX%%categoryassociations` (`associationid`, `productid`, `categoryid`) VALUES (57, 25, 8);
INSERT INTO `%%PREFIX%%categoryassociations` (`associationid`, `productid`, `categoryid`) VALUES (56, 26, 7);
INSERT INTO `%%PREFIX%%categoryassociations` (`associationid`, `productid`, `categoryid`) VALUES (55, 27, 7);
INSERT INTO `%%PREFIX%%categoryassociations` (`associationid`, `productid`, `categoryid`) VALUES (54, 28, 1);

--
-- Dumping data for table `%%PREFIX%%products`
--

INSERT INTO `%%PREFIX%%products` (`productid`, `prodname`, `prodtype`, `prodcode`, `prodfile`, `proddesc`, `prodsearchkeywords`, `prodavailability`, `prodprice`, `prodcostprice`, `prodretailprice`, `prodsaleprice`, `prodcalculatedprice`, `prodistaxable`, `prodsortorder`, `prodvisible`, `prodfeatured`, `prodvendorfeatured`, `prodrelatedproducts`, `prodcurrentinv`, `prodlowinv`, `prodoptionsrequired`, `prodwarranty`, `prodweight`, `prodwidth`, `prodheight`, `proddepth`, `prodfixedshippingcost`, `prodfreeshipping`, `prodinvtrack`, `prodratingtotal`, `prodnumratings`, `prodnumsold`, `proddateadded`, `prodbrandid`, `prodnumviews`, `prodpagetitle`, `prodmetakeywords`, `prodmetadesc`, `prodlayoutfile`, `prodvariationid`, `prodallowpurchases`, `prodhideprice`, `prodcallforpricinglabel`, `prodcatids`, `prodlastmodified`, `prodvendorid`, `prodhastags`, `prodwrapoptions`, `prodconfigfields`) VALUES (1, 'Produto de Teste 01', 1, '', '', 'Esse anuncio e apenas de teste da loja.', '', '', 49.0000, 0.0000, 0.0000, 0.0000, 49.0000, 1, 0, 1, 0, 0, '-1', 0, 0, 1, '', 2.0, 1.6200, 1.0700, 0.4100, 0.0000, 0, 0, 0, 0, 1, 1231755759, 1, 7, '', '', '', 'product.html', '', 1, 0, '', '3', 0, 1, 0, '0', '');
INSERT INTO `%%PREFIX%%products` (`productid`, `prodname`, `prodtype`, `prodcode`, `prodfile`, `proddesc`, `prodsearchkeywords`, `prodavailability`, `prodprice`, `prodcostprice`, `prodretailprice`, `prodsaleprice`, `prodcalculatedprice`, `prodistaxable`, `prodsortorder`, `prodvisible`, `prodfeatured`, `prodvendorfeatured`, `prodrelatedproducts`, `prodcurrentinv`, `prodlowinv`, `prodoptionsrequired`, `prodwarranty`, `prodweight`, `prodwidth`, `prodheight`, `proddepth`, `prodfixedshippingcost`, `prodfreeshipping`, `prodinvtrack`, `prodratingtotal`, `prodnumratings`, `prodnumsold`, `proddateadded`, `prodbrandid`, `prodnumviews`, `prodpagetitle`, `prodmetakeywords`, `prodmetadesc`, `prodlayoutfile`, `prodvariationid`, `prodallowpurchases`, `prodhideprice`, `prodcallforpricinglabel`, `prodcatids`, `prodlastmodified`, `prodvendorid`, `prodhastags`, `prodwrapoptions`, `prodconfigfields`) VALUES (2, 'Produto de Teste 02', 1, '', '', 'Esse anuncio e apenas de teste da loja.', '', '', 149.0000, 0.0000, 0.0000, 0.0000, 149.0000, 1, 0, 1, 1, 0, '-1', 0, 0, 1, '', 1.0, 1.5000, 3.6000, 0.2400, 0.0000, 0, 0, 0, 0, 2, 1231756138, 1, 8, '', '', '', 'product.html', '', 1, 0, '', '3', 0, 1, 0, '0', '');
INSERT INTO `%%PREFIX%%products` (`productid`, `prodname`, `prodtype`, `prodcode`, `prodfile`, `proddesc`, `prodsearchkeywords`, `prodavailability`, `prodprice`, `prodcostprice`, `prodretailprice`, `prodsaleprice`, `prodcalculatedprice`, `prodistaxable`, `prodsortorder`, `prodvisible`, `prodfeatured`, `prodvendorfeatured`, `prodrelatedproducts`, `prodcurrentinv`, `prodlowinv`, `prodoptionsrequired`, `prodwarranty`, `prodweight`, `prodwidth`, `prodheight`, `proddepth`, `prodfixedshippingcost`, `prodfreeshipping`, `prodinvtrack`, `prodratingtotal`, `prodnumratings`, `prodnumsold`, `proddateadded`, `prodbrandid`, `prodnumviews`, `prodpagetitle`, `prodmetakeywords`, `prodmetadesc`, `prodlayoutfile`, `prodvariationid`, `prodallowpurchases`, `prodhideprice`, `prodcallforpricinglabel`, `prodcatids`, `prodlastmodified`, `prodvendorid`, `prodhastags`, `prodwrapoptions`, `prodconfigfields`) VALUES (3, 'Produto de Teste 03', 1, '', '', 'Esse anuncio e apenas de teste da loja.', '', '', 249.0000, 0.0000, 0.0000, 0.0000, 249.0000, 1, 0, 1, 0, 0, '-1', 0, 0, 1, '', 3.0, 2.4000, 4.1000, 0.4100, 0.0000, 0, 0, 0, 0, 3, 1231756862, 1, 2, '', '', '', 'product.html', '', 1, 0, '', '3', 0, 1, 0, '0', '');
INSERT INTO `%%PREFIX%%products` (`productid`, `prodname`, `prodtype`, `prodcode`, `prodfile`, `proddesc`, `prodsearchkeywords`, `prodavailability`, `prodprice`, `prodcostprice`, `prodretailprice`, `prodsaleprice`, `prodcalculatedprice`, `prodistaxable`, `prodsortorder`, `prodvisible`, `prodfeatured`, `prodvendorfeatured`, `prodrelatedproducts`, `prodcurrentinv`, `prodlowinv`, `prodoptionsrequired`, `prodwarranty`, `prodweight`, `prodwidth`, `prodheight`, `proddepth`, `prodfixedshippingcost`, `prodfreeshipping`, `prodinvtrack`, `prodratingtotal`, `prodnumratings`, `prodnumsold`, `proddateadded`, `prodbrandid`, `prodnumviews`, `prodpagetitle`, `prodmetakeywords`, `prodmetadesc`, `prodlayoutfile`, `prodvariationid`, `prodallowpurchases`, `prodhideprice`, `prodcallforpricinglabel`, `prodcatids`, `prodlastmodified`, `prodvendorid`, `prodhastags`, `prodwrapoptions`, `prodconfigfields`) VALUES (4, 'Produto de Teste 04', 1, '', '', 'Esse anuncio e apenas de teste da loja.', '', '', 229.0000, 0.0000, 0.0000, 0.0000, 229.0000, 1, 0, 1, 0, 0, '6,22,23,24', 0, 0, 1, '', 1.5, 2.4000, 4.1000, 0.3000, 0.0000, 0, 0, 0, 0, 4, 1231757201, 1, 2, '', '', '', 'product.html', '', 1, 0, '', '3', 0, 1, 0, '0', '');
INSERT INTO `%%PREFIX%%products` (`productid`, `prodname`, `prodtype`, `prodcode`, `prodfile`, `proddesc`, `prodsearchkeywords`, `prodavailability`, `prodprice`, `prodcostprice`, `prodretailprice`, `prodsaleprice`, `prodcalculatedprice`, `prodistaxable`, `prodsortorder`, `prodvisible`, `prodfeatured`, `prodvendorfeatured`, `prodrelatedproducts`, `prodcurrentinv`, `prodlowinv`, `prodoptionsrequired`, `prodwarranty`, `prodweight`, `prodwidth`, `prodheight`, `proddepth`, `prodfixedshippingcost`, `prodfreeshipping`, `prodinvtrack`, `prodratingtotal`, `prodnumratings`, `prodnumsold`, `proddateadded`, `prodbrandid`, `prodnumviews`, `prodpagetitle`, `prodmetakeywords`, `prodmetadesc`, `prodlayoutfile`, `prodvariationid`, `prodallowpurchases`, `prodhideprice`, `prodcallforpricinglabel`, `prodcatids`, `prodlastmodified`, `prodvendorid`, `prodhastags`, `prodwrapoptions`, `prodconfigfields`) VALUES (5, 'Produto de Teste 05', 1, '', '', 'Esse anuncio e apenas de teste da loja.', '', '', 1299.0000, 0.0000, 0.0000, 0.0000, 1299.0000, 1, 0, 1, 0, 0, '-1', 0, 0, 1, '', 4.5, 12.7800, 0.9000, 8.9400, 0.0000, 0, 0, 0, 0, 5, 1231757800, 1, 5, '', '', '', 'product.html', '', 1, 0, '', '1', 0, 1, 0, '0', '');
INSERT INTO `%%PREFIX%%products` (`productid`, `prodname`, `prodtype`, `prodcode`, `prodfile`, `proddesc`, `prodsearchkeywords`, `prodavailability`, `prodprice`, `prodcostprice`, `prodretailprice`, `prodsaleprice`, `prodcalculatedprice`, `prodistaxable`, `prodsortorder`, `prodvisible`, `prodfeatured`, `prodvendorfeatured`, `prodrelatedproducts`, `prodcurrentinv`, `prodlowinv`, `prodoptionsrequired`, `prodwarranty`, `prodweight`, `prodwidth`, `prodheight`, `proddepth`, `prodfixedshippingcost`, `prodfreeshipping`, `prodinvtrack`, `prodratingtotal`, `prodnumratings`, `prodnumsold`, `proddateadded`, `prodbrandid`, `prodnumviews`, `prodpagetitle`, `prodmetakeywords`, `prodmetadesc`, `prodlayoutfile`, `prodvariationid`, `prodallowpurchases`, `prodhideprice`, `prodcallforpricinglabel`, `prodcatids`, `prodlastmodified`, `prodvendorid`, `prodhastags`, `prodwrapoptions`, `prodconfigfields`) VALUES (6, 'Produto de Teste 06', 1, '', '', 'Esse anuncio e apenas de teste da loja.', '', '', 1999.0000, 0.0000, 0.0000, 0.0000, 1999.0000, 1, 0, 1, 1, 0, '-1', 0, 0, 1, '', 5.5, 14.3500, 0.9500, 9.8200, 0.0000, 0, 0, 0, 0, 6, 1231758196, 1, 4, '', '', '', 'product.html', '', 1, 0, '', '1', 0, 1, 0, '0', '');
INSERT INTO `%%PREFIX%%products` (`productid`, `prodname`, `prodtype`, `prodcode`, `prodfile`, `proddesc`, `prodsearchkeywords`, `prodavailability`, `prodprice`, `prodcostprice`, `prodretailprice`, `prodsaleprice`, `prodcalculatedprice`, `prodistaxable`, `prodsortorder`, `prodvisible`, `prodfeatured`, `prodvendorfeatured`, `prodrelatedproducts`, `prodcurrentinv`, `prodlowinv`, `prodoptionsrequired`, `prodwarranty`, `prodweight`, `prodwidth`, `prodheight`, `proddepth`, `prodfixedshippingcost`, `prodfreeshipping`, `prodinvtrack`, `prodratingtotal`, `prodnumratings`, `prodnumsold`, `proddateadded`, `prodbrandid`, `prodnumviews`, `prodpagetitle`, `prodmetakeywords`, `prodmetadesc`, `prodlayoutfile`, `prodvariationid`, `prodallowpurchases`, `prodhideprice`, `prodcallforpricinglabel`, `prodcatids`, `prodlastmodified`, `prodvendorid`, `prodhastags`, `prodwrapoptions`, `prodconfigfields`) VALUES (7, 'Produto de Teste 07', 1, '', '', 'Esse anuncio e apenas de teste da loja.', '', '', 1799.0000, 0.0000, 0.0000, 0.0000, 1799.0000, 1, 0, 1, 0, 0, '-1', 0, 0, 1, '', 3.0, 12.8000, 0.7600, 8.9400, 0.0000, 0, 0, 0, 0, 7, 1231758729, 1, 3, '', '', '', 'product.html', '', 1, 0, '', '1', 0, 1, 0, '0', '');
INSERT INTO `%%PREFIX%%products` (`productid`, `prodname`, `prodtype`, `prodcode`, `prodfile`, `proddesc`, `prodsearchkeywords`, `prodavailability`, `prodprice`, `prodcostprice`, `prodretailprice`, `prodsaleprice`, `prodcalculatedprice`, `prodistaxable`, `prodsortorder`, `prodvisible`, `prodfeatured`, `prodvendorfeatured`, `prodrelatedproducts`, `prodcurrentinv`, `prodlowinv`, `prodoptionsrequired`, `prodwarranty`, `prodweight`, `prodwidth`, `prodheight`, `proddepth`, `prodfixedshippingcost`, `prodfreeshipping`, `prodinvtrack`, `prodratingtotal`, `prodnumratings`, `prodnumsold`, `proddateadded`, `prodbrandid`, `prodnumviews`, `prodpagetitle`, `prodmetakeywords`, `prodmetadesc`, `prodlayoutfile`, `prodvariationid`, `prodallowpurchases`, `prodhideprice`, `prodcallforpricinglabel`, `prodcatids`, `prodlastmodified`, `prodvendorid`, `prodhastags`, `prodwrapoptions`, `prodconfigfields`) VALUES (8, 'Produto de Teste 08', 1, '', '', 'Esse anuncio e apenas de teste da loja.', '', '', 199.9500, 0.0000, 0.0000, 0.0000, 199.9500, 1, 0, 1, 0, 0, '-1', 0, 0, 1, '', 1.0, 0.0000, 0.0000, 0.0000, 0.0000, 0, 0, 0, 0, 8, 1231759543, 3, 0, '', '', '', 'product.html', '', 1, 0, '', '6', 0, 2, 0, '0', '');
INSERT INTO `%%PREFIX%%products` (`productid`, `prodname`, `prodtype`, `prodcode`, `prodfile`, `proddesc`, `prodsearchkeywords`, `prodavailability`, `prodprice`, `prodcostprice`, `prodretailprice`, `prodsaleprice`, `prodcalculatedprice`, `prodistaxable`, `prodsortorder`, `prodvisible`, `prodfeatured`, `prodvendorfeatured`, `prodrelatedproducts`, `prodcurrentinv`, `prodlowinv`, `prodoptionsrequired`, `prodwarranty`, `prodweight`, `prodwidth`, `prodheight`, `proddepth`, `prodfixedshippingcost`, `prodfreeshipping`, `prodinvtrack`, `prodratingtotal`, `prodnumratings`, `prodnumsold`, `proddateadded`, `prodbrandid`, `prodnumviews`, `prodpagetitle`, `prodmetakeywords`, `prodmetadesc`, `prodlayoutfile`, `prodvariationid`, `prodallowpurchases`, `prodhideprice`, `prodcallforpricinglabel`, `prodcatids`, `prodlastmodified`, `prodvendorid`, `prodhastags`, `prodwrapoptions`, `prodconfigfields`) VALUES (9, 'Produto de Teste 09', 1, '', '', 'Esse anuncio e apenas de teste da loja.', '', '', 429.9500, 0.0000, 0.0000, 0.0000, 429.9500, 1, 0, 1, 0, 0, '-1', 0, 0, 1, '', 2.0, 0.0000, 0.0000, 0.0000, 0.0000, 0, 0, 0, 0, 9, 1231759622, 3, 0, '', '', '', 'product.html', '', 1, 0, '', '6', 0, 2, 0, '0', '');
INSERT INTO `%%PREFIX%%products` (`productid`, `prodname`, `prodtype`, `prodcode`, `prodfile`, `proddesc`, `prodsearchkeywords`, `prodavailability`, `prodprice`, `prodcostprice`, `prodretailprice`, `prodsaleprice`, `prodcalculatedprice`, `prodistaxable`, `prodsortorder`, `prodvisible`, `prodfeatured`, `prodvendorfeatured`, `prodrelatedproducts`, `prodcurrentinv`, `prodlowinv`, `prodoptionsrequired`, `prodwarranty`, `prodweight`, `prodwidth`, `prodheight`, `proddepth`, `prodfixedshippingcost`, `prodfreeshipping`, `prodinvtrack`, `prodratingtotal`, `prodnumratings`, `prodnumsold`, `proddateadded`, `prodbrandid`, `prodnumviews`, `prodpagetitle`, `prodmetakeywords`, `prodmetadesc`, `prodlayoutfile`, `prodvariationid`, `prodallowpurchases`, `prodhideprice`, `prodcallforpricinglabel`, `prodcatids`, `prodlastmodified`, `prodvendorid`, `prodhastags`, `prodwrapoptions`, `prodconfigfields`) VALUES (10, 'Produto de Teste 10', 1, 'OFFICE08-H&S', '', 'Esse anuncio e apenas de teste da loja.', '', '', 229.0000, 0.0000, 0.0000, 0.0000, 229.0000, 1, 0, 1, 0, 0, '-1', 0, 0, 1, '', 1.02, 0.0000, 0.0000, 0.0000, 0.0000, 0, 0, 0, 0, 10, 1231760319, 2, 0, '', '', '', 'product.html', '', 1, 0, '', '9', 0, 4, 0, '0', '');
INSERT INTO `%%PREFIX%%products` (`productid`, `prodname`, `prodtype`, `prodcode`, `prodfile`, `proddesc`, `prodsearchkeywords`, `prodavailability`, `prodprice`, `prodcostprice`, `prodretailprice`, `prodsaleprice`, `prodcalculatedprice`, `prodistaxable`, `prodsortorder`, `prodvisible`, `prodfeatured`, `prodvendorfeatured`, `prodrelatedproducts`, `prodcurrentinv`, `prodlowinv`, `prodoptionsrequired`, `prodwarranty`, `prodweight`, `prodwidth`, `prodheight`, `proddepth`, `prodfixedshippingcost`, `prodfreeshipping`, `prodinvtrack`, `prodratingtotal`, `prodnumratings`, `prodnumsold`, `proddateadded`, `prodbrandid`, `prodnumviews`, `prodpagetitle`, `prodmetakeywords`, `prodmetadesc`, `prodlayoutfile`, `prodvariationid`, `prodallowpurchases`, `prodhideprice`, `prodcallforpricinglabel`, `prodcatids`, `prodlastmodified`, `prodvendorid`, `prodhastags`, `prodwrapoptions`, `prodconfigfields`) VALUES (11, 'Produto de Teste 11', 1, '', '', 'Esse anuncio e apenas de teste da loja.', '', '', 499.9500, 0.0000, 0.0000, 0.0000, 499.9500, 1, 0, 1, 0, 0, '-1', 0, 0, 1, '', 2.10, 0.0000, 0.0000, 0.0000, 0.0000, 0, 0, 0, 0, 11, 1231760577, 2, 0, '', '', '', 'product.html', '', 1, 0, '', '9', 0, 4, 0, '0', '');
INSERT INTO `%%PREFIX%%products` (`productid`, `prodname`, `prodtype`, `prodcode`, `prodfile`, `proddesc`, `prodsearchkeywords`, `prodavailability`, `prodprice`, `prodcostprice`, `prodretailprice`, `prodsaleprice`, `prodcalculatedprice`, `prodistaxable`, `prodsortorder`, `prodvisible`, `prodfeatured`, `prodvendorfeatured`, `prodrelatedproducts`, `prodcurrentinv`, `prodlowinv`, `prodoptionsrequired`, `prodwarranty`, `prodweight`, `prodwidth`, `prodheight`, `proddepth`, `prodfixedshippingcost`, `prodfreeshipping`, `prodinvtrack`, `prodratingtotal`, `prodnumratings`, `prodnumsold`, `proddateadded`, `prodbrandid`, `prodnumviews`, `prodpagetitle`, `prodmetakeywords`, `prodmetadesc`, `prodlayoutfile`, `prodvariationid`, `prodallowpurchases`, `prodhideprice`, `prodcallforpricinglabel`, `prodcatids`, `prodlastmodified`, `prodvendorid`, `prodhastags`, `prodwrapoptions`, `prodconfigfields`) VALUES (12, 'Produto de Teste 12', 1, 'IWORK09', '', 'Esse anuncio e apenas de teste da loja.', '', '', 79.0000, 0.0000, 0.0000, 0.0000, 79.0000, 1, 0, 1, 0, 0, '-1', 0, 0, 1, '', 4.01, 0.0000, 0.0000, 0.0000, 0.0000, 0, 0, 0, 0, 12, 1231760717, 1, 0, '', '', '', 'product.html', '', 1, 0, '', '9', 0, 1, 0, '0', '');
INSERT INTO `%%PREFIX%%products` (`productid`, `prodname`, `prodtype`, `prodcode`, `prodfile`, `proddesc`, `prodsearchkeywords`, `prodavailability`, `prodprice`, `prodcostprice`, `prodretailprice`, `prodsaleprice`, `prodcalculatedprice`, `prodistaxable`, `prodsortorder`, `prodvisible`, `prodfeatured`, `prodvendorfeatured`, `prodrelatedproducts`, `prodcurrentinv`, `prodlowinv`, `prodoptionsrequired`, `prodwarranty`, `prodweight`, `prodwidth`, `prodheight`, `proddepth`, `prodfixedshippingcost`, `prodfreeshipping`, `prodinvtrack`, `prodratingtotal`, `prodnumratings`, `prodnumsold`, `proddateadded`, `prodbrandid`, `prodnumviews`, `prodpagetitle`, `prodmetakeywords`, `prodmetadesc`, `prodlayoutfile`, `prodvariationid`, `prodallowpurchases`, `prodhideprice`, `prodcallforpricinglabel`, `prodcatids`, `prodlastmodified`, `prodvendorid`, `prodhastags`, `prodwrapoptions`, `prodconfigfields`) VALUES (13, 'Produto de Teste 13', 1, 'ILIFE09', '', 'Esse anuncio e apenas de teste da loja.', '', '', 79.0000, 0.0000, 0.0000, 0.0000, 79.0000, 1, 0, 1, 0, 0, '-1', 0, 0, 1, '', 6.01, 0.0000, 0.0000, 0.0000, 0.0000, 0, 0, 0, 0, 13, 1231760828, 1, 0, '', '', '', 'product.html', '', 1, 0, '', '9', 0, 1, 0, '0', '');
INSERT INTO `%%PREFIX%%products` (`productid`, `prodname`, `prodtype`, `prodcode`, `prodfile`, `proddesc`, `prodsearchkeywords`, `prodavailability`, `prodprice`, `prodcostprice`, `prodretailprice`, `prodsaleprice`, `prodcalculatedprice`, `prodistaxable`, `prodsortorder`, `prodvisible`, `prodfeatured`, `prodvendorfeatured`, `prodrelatedproducts`, `prodcurrentinv`, `prodlowinv`, `prodoptionsrequired`, `prodwarranty`, `prodweight`, `prodwidth`, `prodheight`, `proddepth`, `prodfixedshippingcost`, `prodfreeshipping`, `prodinvtrack`, `prodratingtotal`, `prodnumratings`, `prodnumsold`, `proddateadded`, `prodbrandid`, `prodnumviews`, `prodpagetitle`, `prodmetakeywords`, `prodmetadesc`, `prodlayoutfile`, `prodvariationid`, `prodallowpurchases`, `prodhideprice`, `prodcallforpricinglabel`, `prodcatids`, `prodlastmodified`, `prodvendorid`, `prodhastags`, `prodwrapoptions`, `prodconfigfields`) VALUES (14, 'Produto de Teste 14', 1, 'MIGHTYMOUSE', '', 'Esse anuncio e apenas de teste da loja.', '', '', 69.0000, 0.0000, 0.0000, 0.0000, 69.0000, 1, 0, 1, 0, 0, '-1', 0, 0, 1, '', 2.0, 0.0000, 0.0000, 0.0000, 0.0000, 0, 0, 0, 0, 14, 1231761029, 1, 0, '', '', '', 'product.html', '', 1, 0, '', '4', 0, 1, 0, '0', '');
INSERT INTO `%%PREFIX%%products` (`productid`, `prodname`, `prodtype`, `prodcode`, `prodfile`, `proddesc`, `prodsearchkeywords`, `prodavailability`, `prodprice`, `prodcostprice`, `prodretailprice`, `prodsaleprice`, `prodcalculatedprice`, `prodistaxable`, `prodsortorder`, `prodvisible`, `prodfeatured`, `prodvendorfeatured`, `prodrelatedproducts`, `prodcurrentinv`, `prodlowinv`, `prodoptionsrequired`, `prodwarranty`, `prodweight`, `prodwidth`, `prodheight`, `proddepth`, `prodfixedshippingcost`, `prodfreeshipping`, `prodinvtrack`, `prodratingtotal`, `prodnumratings`, `prodnumsold`, `proddateadded`, `prodbrandid`, `prodnumviews`, `prodpagetitle`, `prodmetakeywords`, `prodmetadesc`, `prodlayoutfile`, `prodvariationid`, `prodallowpurchases`, `prodhideprice`, `prodcallforpricinglabel`, `prodcatids`, `prodlastmodified`, `prodvendorid`, `prodhastags`, `prodwrapoptions`, `prodconfigfields`) VALUES (15, 'Produto de Teste 15', 1, 'WIRELESS-MIGHTY', '', 'Esse anuncio e apenas de teste da loja.', '', '', 99.0000, 0.0000, 0.0000, 0.0000, 99.0000, 1, 0, 1, 0, 0, '-1', 0, 0, 1, '', 3.0, 0.0000, 0.0000, 0.0000, 0.0000, 0, 0, 0, 0, 15, 1231761152, 1, 0, '', '', '', 'product.html', '', 1, 0, '', '4', 0, 0, 0, '0', '');
INSERT INTO `%%PREFIX%%products` (`productid`, `prodname`, `prodtype`, `prodcode`, `prodfile`, `proddesc`, `prodsearchkeywords`, `prodavailability`, `prodprice`, `prodcostprice`, `prodretailprice`, `prodsaleprice`, `prodcalculatedprice`, `prodistaxable`, `prodsortorder`, `prodvisible`, `prodfeatured`, `prodvendorfeatured`, `prodrelatedproducts`, `prodcurrentinv`, `prodlowinv`, `prodoptionsrequired`, `prodwarranty`, `prodweight`, `prodwidth`, `prodheight`, `proddepth`, `prodfixedshippingcost`, `prodfreeshipping`, `prodinvtrack`, `prodratingtotal`, `prodnumratings`, `prodnumsold`, `proddateadded`, `prodbrandid`, `prodnumviews`, `prodpagetitle`, `prodmetakeywords`, `prodmetadesc`, `prodlayoutfile`, `prodvariationid`, `prodallowpurchases`, `prodhideprice`, `prodcallforpricinglabel`, `prodcatids`, `prodlastmodified`, `prodvendorid`, `prodhastags`, `prodwrapoptions`, `prodconfigfields`) VALUES (16, 'Produto de Teste 16', 1, 'LOGITECH-NANO', '', 'Esse anuncio e apenas de teste da loja.', '', '', 69.9600, 0.0000, 0.0000, 0.0000, 69.9600, 1, 0, 1, 0, 0, '-1', 0, 0, 1, '', 2.1, 0.0000, 0.0000, 0.0000, 0.0000, 0, 0, 0, 0, 16, 1231761332, 4, 0, '', '', '', 'product.html', '', 1, 0, '', '4', 0, 3, 0, '0', '');
INSERT INTO `%%PREFIX%%products` (`productid`, `prodname`, `prodtype`, `prodcode`, `prodfile`, `proddesc`, `prodsearchkeywords`, `prodavailability`, `prodprice`, `prodcostprice`, `prodretailprice`, `prodsaleprice`, `prodcalculatedprice`, `prodistaxable`, `prodsortorder`, `prodvisible`, `prodfeatured`, `prodvendorfeatured`, `prodrelatedproducts`, `prodcurrentinv`, `prodlowinv`, `prodoptionsrequired`, `prodwarranty`, `prodweight`, `prodwidth`, `prodheight`, `proddepth`, `prodfixedshippingcost`, `prodfreeshipping`, `prodinvtrack`, `prodratingtotal`, `prodnumratings`, `prodnumsold`, `proddateadded`, `prodbrandid`, `prodnumviews`, `prodpagetitle`, `prodmetakeywords`, `prodmetadesc`, `prodlayoutfile`, `prodvariationid`, `prodallowpurchases`, `prodhideprice`, `prodcallforpricinglabel`, `prodcatids`, `prodlastmodified`, `prodvendorid`, `prodhastags`, `prodwrapoptions`, `prodconfigfields`) VALUES (17, 'Produto de Teste 17', 1, 'WIRELESS-KEYBOARD', '', 'Esse anuncio e apenas de teste da loja.', '', '', 79.0000, 0.0000, 0.0000, 0.0000, 79.0000, 1, 0, 1, 0, 0, '-1', 0, 0, 1, '', 4.0, 0.0000, 0.0000, 0.0000, 0.0000, 0, 0, 0, 0, 17, 1231761543, 1, 1, '', '', '', 'product.html', '', 1, 0, '', '4', 0, 0, 0, '0', '');
INSERT INTO `%%PREFIX%%products` (`productid`, `prodname`, `prodtype`, `prodcode`, `prodfile`, `proddesc`, `prodsearchkeywords`, `prodavailability`, `prodprice`, `prodcostprice`, `prodretailprice`, `prodsaleprice`, `prodcalculatedprice`, `prodistaxable`, `prodsortorder`, `prodvisible`, `prodfeatured`, `prodvendorfeatured`, `prodrelatedproducts`, `prodcurrentinv`, `prodlowinv`, `prodoptionsrequired`, `prodwarranty`, `prodweight`, `prodwidth`, `prodheight`, `proddepth`, `prodfixedshippingcost`, `prodfreeshipping`, `prodinvtrack`, `prodratingtotal`, `prodnumratings`, `prodnumsold`, `proddateadded`, `prodbrandid`, `prodnumviews`, `prodpagetitle`, `prodmetakeywords`, `prodmetadesc`, `prodlayoutfile`, `prodvariationid`, `prodallowpurchases`, `prodhideprice`, `prodcallforpricinglabel`, `prodcatids`, `prodlastmodified`, `prodvendorid`, `prodhastags`, `prodwrapoptions`, `prodconfigfields`) VALUES (18, 'Produto de Teste 18', 1, 'CRUMPLER-EMB', '', 'Esse anuncio e apenas de teste da loja.', '', '', 89.9500, 0.0000, 0.0000, 0.0000, 89.9500, 1, 0, 1, 1, 0, '-1', 0, 0, 1, '', 5.0, 0.0000, 0.0000, 0.0000, 0.0000, 0, 0, 0, 0, 18, 1231761944, 5, 0, '', '', '', 'product.html', '', 1, 0, '', '5', 0, 0, 0, '0', '');
INSERT INTO `%%PREFIX%%products` (`productid`, `prodname`, `prodtype`, `prodcode`, `prodfile`, `proddesc`, `prodsearchkeywords`, `prodavailability`, `prodprice`, `prodcostprice`, `prodretailprice`, `prodsaleprice`, `prodcalculatedprice`, `prodistaxable`, `prodsortorder`, `prodvisible`, `prodfeatured`, `prodvendorfeatured`, `prodrelatedproducts`, `prodcurrentinv`, `prodlowinv`, `prodoptionsrequired`, `prodwarranty`, `prodweight`, `prodwidth`, `prodheight`, `proddepth`, `prodfixedshippingcost`, `prodfreeshipping`, `prodinvtrack`, `prodratingtotal`, `prodnumratings`, `prodnumsold`, `proddateadded`, `prodbrandid`, `prodnumviews`, `prodpagetitle`, `prodmetakeywords`, `prodmetadesc`, `prodlayoutfile`, `prodvariationid`, `prodallowpurchases`, `prodhideprice`, `prodcallforpricinglabel`, `prodcatids`, `prodlastmodified`, `prodvendorid`, `prodhastags`, `prodwrapoptions`, `prodconfigfields`) VALUES (19, 'Produto de Teste 19', 1, '', '', 'Esse anuncio e apenas de teste da loja.', '', '', 39.9500, 0.0000, 0.0000, 0.0000, 39.9500, 1, 0, 1, 0, 0, '-1', 0, 0, 1, '', 3.0, 0.0000, 0.0000, 0.0000, 0.0000, 0, 0, 0, 0, 19, 1231762065, 6, 0, '', '', '', 'product.html', '', 1, 0, '', '5', 0, 0, 0, '0', '');
INSERT INTO `%%PREFIX%%products` (`productid`, `prodname`, `prodtype`, `prodcode`, `prodfile`, `proddesc`, `prodsearchkeywords`, `prodavailability`, `prodprice`, `prodcostprice`, `prodretailprice`, `prodsaleprice`, `prodcalculatedprice`, `prodistaxable`, `prodsortorder`, `prodvisible`, `prodfeatured`, `prodvendorfeatured`, `prodrelatedproducts`, `prodcurrentinv`, `prodlowinv`, `prodoptionsrequired`, `prodwarranty`, `prodweight`, `prodwidth`, `prodheight`, `proddepth`, `prodfixedshippingcost`, `prodfreeshipping`, `prodinvtrack`, `prodratingtotal`, `prodnumratings`, `prodnumsold`, `proddateadded`, `prodbrandid`, `prodnumviews`, `prodpagetitle`, `prodmetakeywords`, `prodmetadesc`, `prodlayoutfile`, `prodvariationid`, `prodallowpurchases`, `prodhideprice`, `prodcallforpricinglabel`, `prodcatids`, `prodlastmodified`, `prodvendorid`, `prodhastags`, `prodwrapoptions`, `prodconfigfields`) VALUES (20, 'Produto de Teste 20', 1, 'SPEC-13-B', '', 'Esse anuncio e apenas de teste da loja.', '', '', 49.9500, 0.0000, 0.0000, 0.0000, 49.9500, 1, 0, 1, 0, 0, '-1', 0, 0, 1, '', 1.01, 0.0000, 0.0000, 0.0000, 0.0000, 0, 0, 0, 0, 20, 1231762165, 7, 0, '', '', '', 'product.html', '', 1, 0, '', '5', 0, 0, 0, '0', '');
INSERT INTO `%%PREFIX%%products` (`productid`, `prodname`, `prodtype`, `prodcode`, `prodfile`, `proddesc`, `prodsearchkeywords`, `prodavailability`, `prodprice`, `prodcostprice`, `prodretailprice`, `prodsaleprice`, `prodcalculatedprice`, `prodistaxable`, `prodsortorder`, `prodvisible`, `prodfeatured`, `prodvendorfeatured`, `prodrelatedproducts`, `prodcurrentinv`, `prodlowinv`, `prodoptionsrequired`, `prodwarranty`, `prodweight`, `prodwidth`, `prodheight`, `proddepth`, `prodfixedshippingcost`, `prodfreeshipping`, `prodinvtrack`, `prodratingtotal`, `prodnumratings`, `prodnumsold`, `proddateadded`, `prodbrandid`, `prodnumviews`, `prodpagetitle`, `prodmetakeywords`, `prodmetadesc`, `prodlayoutfile`, `prodvariationid`, `prodallowpurchases`, `prodhideprice`, `prodcallforpricinglabel`, `prodcatids`, `prodlastmodified`, `prodvendorid`, `prodhastags`, `prodwrapoptions`, `prodconfigfields`) VALUES (21, 'Produto de Teste 21', 1, 'BOOQ-MAMBO', '', 'Esse anuncio e apenas de teste da loja.', '', '', 124.9500, 0.0000, 0.0000, 0.0000, 124.9500, 1, 0, 1, 0, 0, '-1', 0, 0, 1, '', 2.01, 0.0000, 0.0000, 0.0000, 0.0000, 0, 0, 0, 0, 21, 1231762274, 8, 0, '', '', '', 'product.html', '', 1, 0, '', '5', 0, 0, 0, '0', '');
INSERT INTO `%%PREFIX%%products` (`productid`, `prodname`, `prodtype`, `prodcode`, `prodfile`, `proddesc`, `prodsearchkeywords`, `prodavailability`, `prodprice`, `prodcostprice`, `prodretailprice`, `prodsaleprice`, `prodcalculatedprice`, `prodistaxable`, `prodsortorder`, `prodvisible`, `prodfeatured`, `prodvendorfeatured`, `prodrelatedproducts`, `prodcurrentinv`, `prodlowinv`, `prodoptionsrequired`, `prodwarranty`, `prodweight`, `prodwidth`, `prodheight`, `proddepth`, `prodfixedshippingcost`, `prodfreeshipping`, `prodinvtrack`, `prodratingtotal`, `prodnumratings`, `prodnumsold`, `proddateadded`, `prodbrandid`, `prodnumviews`, `prodpagetitle`, `prodmetakeywords`, `prodmetadesc`, `prodlayoutfile`, `prodvariationid`, `prodallowpurchases`, `prodhideprice`, `prodcallforpricinglabel`, `prodcatids`, `prodlastmodified`, `prodvendorid`, `prodhastags`, `prodwrapoptions`, `prodconfigfields`) VALUES (22, 'Produto de Teste 22', 1, 'PUREFI', '', 'Esse anuncio e apenas de teste da loja.', '', '', 129.9500, 0.0000, 0.0000, 0.0000, 129.9500, 1, 0, 1, 0, 0, '-1', 0, 0, 1, '', 1.6, 13.2000, 3.6000, 1.5000, 0.0000, 0, 0, 0, 0, 22, 1231762483, 4, 0, '', '', '', 'product.html', '', 1, 0, '', '7,8', 0, 3, 0, '0', '');
INSERT INTO `%%PREFIX%%products` (`productid`, `prodname`, `prodtype`, `prodcode`, `prodfile`, `proddesc`, `prodsearchkeywords`, `prodavailability`, `prodprice`, `prodcostprice`, `prodretailprice`, `prodsaleprice`, `prodcalculatedprice`, `prodistaxable`, `prodsortorder`, `prodvisible`, `prodfeatured`, `prodvendorfeatured`, `prodrelatedproducts`, `prodcurrentinv`, `prodlowinv`, `prodoptionsrequired`, `prodwarranty`, `prodweight`, `prodwidth`, `prodheight`, `proddepth`, `prodfixedshippingcost`, `prodfreeshipping`, `prodinvtrack`, `prodratingtotal`, `prodnumratings`, `prodnumsold`, `proddateadded`, `prodbrandid`, `prodnumviews`, `prodpagetitle`, `prodmetakeywords`, `prodmetadesc`, `prodlayoutfile`, `prodvariationid`, `prodallowpurchases`, `prodhideprice`, `prodcallforpricinglabel`, `prodcatids`, `prodlastmodified`, `prodvendorid`, `prodhastags`, `prodwrapoptions`, `prodconfigfields`) VALUES (23, 'Produto de Teste 23', 1, 'APPLE-INEAR', '', 'Esse anuncio e apenas de teste da loja.', '', '', 79.0000, 0.0000, 0.0000, 0.0000, 79.0000, 1, 0, 1, 0, 0, '-1', 0, 0, 1, '', 1.0, 0.0000, 0.0000, 0.0000, 0.0000, 0, 0, 0, 0, 23, 1231762609, 1, 0, '', '', '', 'product.html', '', 1, 0, '', '7,8', 0, 1, 0, '0', '');
INSERT INTO `%%PREFIX%%products` (`productid`, `prodname`, `prodtype`, `prodcode`, `prodfile`, `proddesc`, `prodsearchkeywords`, `prodavailability`, `prodprice`, `prodcostprice`, `prodretailprice`, `prodsaleprice`, `prodcalculatedprice`, `prodistaxable`, `prodsortorder`, `prodvisible`, `prodfeatured`, `prodvendorfeatured`, `prodrelatedproducts`, `prodcurrentinv`, `prodlowinv`, `prodoptionsrequired`, `prodwarranty`, `prodweight`, `prodwidth`, `prodheight`, `proddepth`, `prodfixedshippingcost`, `prodfreeshipping`, `prodinvtrack`, `prodratingtotal`, `prodnumratings`, `prodnumsold`, `proddateadded`, `prodbrandid`, `prodnumviews`, `prodpagetitle`, `prodmetakeywords`, `prodmetadesc`, `prodlayoutfile`, `prodvariationid`, `prodallowpurchases`, `prodhideprice`, `prodcallforpricinglabel`, `prodcatids`, `prodlastmodified`, `prodvendorid`, `prodhastags`, `prodwrapoptions`, `prodconfigfields`) VALUES (24, 'Produto de Teste 24', 1, 'IPOD-SOCKS', '', 'Esse anuncio e apenas de teste da loja.', '', '', 29.0000, 0.0000, 0.0000, 0.0000, 29.0000, 1, 0, 1, 1, 0, '-1', 0, 0, 1, '', 1.2, 0.0000, 0.0000, 0.0000, 0.0000, 0, 0, 0, 0, 24, 1231762724, 1, 0, '', '', '', 'product.html', '', 1, 0, '', '8', 0, 1, 0, '0', '');
INSERT INTO `%%PREFIX%%products` (`productid`, `prodname`, `prodtype`, `prodcode`, `prodfile`, `proddesc`, `prodsearchkeywords`, `prodavailability`, `prodprice`, `prodcostprice`, `prodretailprice`, `prodsaleprice`, `prodcalculatedprice`, `prodistaxable`, `prodsortorder`, `prodvisible`, `prodfeatured`, `prodvendorfeatured`, `prodrelatedproducts`, `prodcurrentinv`, `prodlowinv`, `prodoptionsrequired`, `prodwarranty`, `prodweight`, `prodwidth`, `prodheight`, `proddepth`, `prodfixedshippingcost`, `prodfreeshipping`, `prodinvtrack`, `prodratingtotal`, `prodnumratings`, `prodnumsold`, `proddateadded`, `prodbrandid`, `prodnumviews`, `prodpagetitle`, `prodmetakeywords`, `prodmetadesc`, `prodlayoutfile`, `prodvariationid`, `prodallowpurchases`, `prodhideprice`, `prodcallforpricinglabel`, `prodcatids`, `prodlastmodified`, `prodvendorid`, `prodhastags`, `prodwrapoptions`, `prodconfigfields`) VALUES (25, 'Produto de Teste 25', 1, 'INCASE-NANO', '', 'Esse anuncio e apenas de teste da loja.', '', '', 29.9500, 0.0000, 0.0000, 0.0000, 29.9500, 1, 0, 1, 0, 0, '-1', 0, 0, 1, '', 2.05, 0.0000, 0.0000, 0.0000, 0.0000, 0, 0, 0, 0, 25, 1231762873, 9, 0, '', '', '', 'product.html', '', 1, 0, '', '8', 0, 0, 0, '0', '');
INSERT INTO `%%PREFIX%%products` (`productid`, `prodname`, `prodtype`, `prodcode`, `prodfile`, `proddesc`, `prodsearchkeywords`, `prodavailability`, `prodprice`, `prodcostprice`, `prodretailprice`, `prodsaleprice`, `prodcalculatedprice`, `prodistaxable`, `prodsortorder`, `prodvisible`, `prodfeatured`, `prodvendorfeatured`, `prodrelatedproducts`, `prodcurrentinv`, `prodlowinv`, `prodoptionsrequired`, `prodwarranty`, `prodweight`, `prodwidth`, `prodheight`, `proddepth`, `prodfixedshippingcost`, `prodfreeshipping`, `prodinvtrack`, `prodratingtotal`, `prodnumratings`, `prodnumsold`, `proddateadded`, `prodbrandid`, `prodnumviews`, `prodpagetitle`, `prodmetakeywords`, `prodmetadesc`, `prodlayoutfile`, `prodvariationid`, `prodallowpurchases`, `prodhideprice`, `prodcallforpricinglabel`, `prodcatids`, `prodlastmodified`, `prodvendorid`, `prodhastags`, `prodwrapoptions`, `prodconfigfields`) VALUES (26, 'Produto de Teste 26', 1, 'SPECK-IPHONE', '', 'Esse anuncio e apenas de teste da loja.', '', '', 24.9500, 0.0000, 0.0000, 0.0000, 24.9500, 1, 0, 1, 0, 0, '-1', 0, 0, 1, '', 3.01, 0.0000, 0.0000, 0.0000, 0.0000, 0, 0, 0, 0, 26, 1231763092, 7, 0, '', '', '', 'product.html', '', 1, 0, '', '7', 0, 0, 0, '0', '');
INSERT INTO `%%PREFIX%%products` (`productid`, `prodname`, `prodtype`, `prodcode`, `prodfile`, `proddesc`, `prodsearchkeywords`, `prodavailability`, `prodprice`, `prodcostprice`, `prodretailprice`, `prodsaleprice`, `prodcalculatedprice`, `prodistaxable`, `prodsortorder`, `prodvisible`, `prodfeatured`, `prodvendorfeatured`, `prodrelatedproducts`, `prodcurrentinv`, `prodlowinv`, `prodoptionsrequired`, `prodwarranty`, `prodweight`, `prodwidth`, `prodheight`, `proddepth`, `prodfixedshippingcost`, `prodfreeshipping`, `prodinvtrack`, `prodratingtotal`, `prodnumratings`, `prodnumsold`, `proddateadded`, `prodbrandid`, `prodnumviews`, `prodpagetitle`, `prodmetakeywords`, `prodmetadesc`, `prodlayoutfile`, `prodvariationid`, `prodallowpurchases`, `prodhideprice`, `prodcallforpricinglabel`, `prodcatids`, `prodlastmodified`, `prodvendorid`, `prodhastags`, `prodwrapoptions`, `prodconfigfields`) VALUES (27, 'Produto de Teste 27', 1, 'APPLE-BLUE', '', 'Esse anuncio e apenas de teste da loja.', '', '', 99.0000, 0.0000, 0.0000, 0.0000, 99.0000, 1, 0, 1, 0, 0, '-1', 0, 0, 1, '', 2.01, 0.0000, 0.0000, 0.0000, 0.0000, 0, 0, 0, 0, 27, 1231763168, 1, 0, '', '', '', 'product.html', '', 1, 0, '', '7', 0, 0, 0, '0', '');
INSERT INTO `%%PREFIX%%products` (`productid`, `prodname`, `prodtype`, `prodcode`, `prodfile`, `proddesc`, `prodsearchkeywords`, `prodavailability`, `prodprice`, `prodcostprice`, `prodretailprice`, `prodsaleprice`, `prodcalculatedprice`, `prodistaxable`, `prodsortorder`, `prodvisible`, `prodfeatured`, `prodvendorfeatured`, `prodrelatedproducts`, `prodcurrentinv`, `prodlowinv`, `prodoptionsrequired`, `prodwarranty`, `prodweight`, `prodwidth`, `prodheight`, `proddepth`, `prodfixedshippingcost`, `prodfreeshipping`, `prodinvtrack`, `prodratingtotal`, `prodnumratings`, `prodnumsold`, `proddateadded`, `prodbrandid`, `prodnumviews`, `prodpagetitle`, `prodmetakeywords`, `prodmetadesc`, `prodlayoutfile`, `prodvariationid`, `prodallowpurchases`, `prodhideprice`, `prodcallforpricinglabel`, `prodcatids`, `prodlastmodified`, `prodvendorid`, `prodhastags`, `prodwrapoptions`, `prodconfigfields`) VALUES (28, 'Produto de Teste 28', 1, 'MAC-PRO', '', 'Esse anuncio e apenas de teste da loja.', '', '', 2799.0000, 0.0000, 0.0000, 0.0000, 2799.0000, 1, 0, 1, 0, 0, '-1', 0, 0, 1, '', 10.10, 0.0000, 0.0000, 0.0000, 0.0000, 0, 0, 0, 0, 28, 1231812464, 1, 0, '', '', '', 'product.html', '', 1, 0, '', '1', 0, 1, 0, '0', '');

INSERT INTO `%%PREFIX%%product_images` (`imageid`, `imageprodid`, `imageprodhash`, `imagefile`, `imageisthumb`, `imagesort`, `imagefiletiny`, `imagefilethumb`, `imagefilestd`, `imagefilezoom`, `imagedesc`, `imagedateadded`, `imagefiletinysize`, `imagefilethumbsize`, `imagefilestdsize`, `imagefilezoomsize`) VALUES(5, 28, '', 'sample_images/picture_1__48492.png', 1, 0, '', '', '', '', '', 1256533712, '', '', '', '');
INSERT INTO `%%PREFIX%%product_images` (`imageid`, `imageprodid`, `imageprodhash`, `imagefile`, `imageisthumb`, `imagesort`, `imagefiletiny`, `imagefilethumb`, `imagefilestd`, `imagefilezoom`, `imagedesc`, `imagedateadded`, `imagefiletinysize`, `imagefilethumbsize`, `imagefilestdsize`, `imagefilezoomsize`) VALUES(6, 28, '', 'sample_images/overview_hero__21040.jpg', 0, 1, '', '', '', '', '', 1256533712, '', '', '', '');
INSERT INTO `%%PREFIX%%product_images` (`imageid`, `imageprodid`, `imageprodhash`, `imagefile`, `imageisthumb`, `imagesort`, `imagefiletiny`, `imagefilethumb`, `imagefilestd`, `imagefilezoom`, `imagedesc`, `imagedateadded`, `imagefiletinysize`, `imagefilethumbsize`, `imagefilestdsize`, `imagefilezoomsize`) VALUES(7, 28, '', 'sample_images/overview_interior__26831.jpg', 0, 2, '', '', '', '', '', 1256533712, '', '', '', '');
INSERT INTO `%%PREFIX%%product_images` (`imageid`, `imageprodid`, `imageprodhash`, `imagefile`, `imageisthumb`, `imagesort`, `imagefiletiny`, `imagefilethumb`, `imagefilestd`, `imagefilezoom`, `imagedesc`, `imagedateadded`, `imagefiletinysize`, `imagefilethumbsize`, `imagefilestdsize`, `imagefilezoomsize`) VALUES(10, 27, '', 'sample_images/bluetooth__14435.jpg', 1, 0, '', '', '', '', '', 1256533712, '', '', '', '');
INSERT INTO `%%PREFIX%%product_images` (`imageid`, `imageprodid`, `imageprodhash`, `imagefile`, `imageisthumb`, `imagesort`, `imagefiletiny`, `imagefilethumb`, `imagefilestd`, `imagefilezoom`, `imagedesc`, `imagedateadded`, `imagefiletinysize`, `imagefilethumbsize`, `imagefilestdsize`, `imagefilezoomsize`) VALUES(13, 26, '', 'sample_images/speckpi__55102.jpg', 1, 0, '', '', '', '', '', 1256533712, '', '', '', '');
INSERT INTO `%%PREFIX%%product_images` (`imageid`, `imageprodid`, `imageprodhash`, `imagefile`, `imageisthumb`, `imagesort`, `imagefiletiny`, `imagefilethumb`, `imagefilestd`, `imagefilezoom`, `imagedesc`, `imagedateadded`, `imagefiletinysize`, `imagefilethumbsize`, `imagefilestdsize`, `imagefilezoomsize`) VALUES(16, 25, '', 'sample_images/incase__21230.jpg', 1, 0, '', '', '', '', '', 1256533712, '', '', '', '');
INSERT INTO `%%PREFIX%%product_images` (`imageid`, `imageprodid`, `imageprodhash`, `imagefile`, `imageisthumb`, `imagesort`, `imagefiletiny`, `imagefilethumb`, `imagefilestd`, `imagefilezoom`, `imagedesc`, `imagedateadded`, `imagefiletinysize`, `imagefilethumbsize`, `imagefilestdsize`, `imagefilezoomsize`) VALUES(19, 24, '', 'sample_images/ipodsocks__25675.jpg', 1, 0, '', '', '', '', '', 1256533712, '', '', '', '');
INSERT INTO `%%PREFIX%%product_images` (`imageid`, `imageprodid`, `imageprodhash`, `imagefile`, `imageisthumb`, `imagesort`, `imagefiletiny`, `imagefilethumb`, `imagefilestd`, `imagefilezoom`, `imagedesc`, `imagedateadded`, `imagefiletinysize`, `imagefilethumbsize`, `imagefilestdsize`, `imagefilezoomsize`) VALUES(22, 23, '', 'sample_images/earphones1__69201.jpg', 1, 0, '', '', '', '', '', 1256533712, '', '', '', '');
INSERT INTO `%%PREFIX%%product_images` (`imageid`, `imageprodid`, `imageprodhash`, `imagefile`, `imageisthumb`, `imagesort`, `imagefiletiny`, `imagefilethumb`, `imagefilestd`, `imagefilezoom`, `imagedesc`, `imagedateadded`, `imagefiletinysize`, `imagefilethumbsize`, `imagefilestdsize`, `imagefilezoomsize`) VALUES(23, 23, '', 'sample_images/earphones2__31595.jpg', 0, 1, '', '', '', '', '', 1256533712, '', '', '', '');
INSERT INTO `%%PREFIX%%product_images` (`imageid`, `imageprodid`, `imageprodhash`, `imagefile`, `imageisthumb`, `imagesort`, `imagefiletiny`, `imagefilethumb`, `imagefilestd`, `imagefilezoom`, `imagedesc`, `imagedateadded`, `imagefiletinysize`, `imagefilethumbsize`, `imagefilestdsize`, `imagefilezoomsize`) VALUES(29, 22, '', 'sample_images/logitechpure__15425.jpg', 1, 0, '', '', '', '', '', 1256533712, '', '', '', '');
INSERT INTO `%%PREFIX%%product_images` (`imageid`, `imageprodid`, `imageprodhash`, `imagefile`, `imageisthumb`, `imagesort`, `imagefiletiny`, `imagefilethumb`, `imagefilestd`, `imagefilezoom`, `imagedesc`, `imagedateadded`, `imagefiletinysize`, `imagefilethumbsize`, `imagefilestdsize`, `imagefilezoomsize`) VALUES(32, 21, '', 'sample_images/booq__77711.jpg', 1, 0, '', '', '', '', '', 1256533712, '', '', '', '');
INSERT INTO `%%PREFIX%%product_images` (`imageid`, `imageprodid`, `imageprodhash`, `imagefile`, `imageisthumb`, `imagesort`, `imagefiletiny`, `imagefilethumb`, `imagefilestd`, `imagefilezoom`, `imagedesc`, `imagedateadded`, `imagefiletinysize`, `imagefilethumbsize`, `imagefilestdsize`, `imagefilezoomsize`) VALUES(35, 20, '', 'sample_images/speck__64014.jpg', 1, 0, '', '', '', '', '', 1256533712, '', '', '', '');
INSERT INTO `%%PREFIX%%product_images` (`imageid`, `imageprodid`, `imageprodhash`, `imagefile`, `imageisthumb`, `imagesort`, `imagefiletiny`, `imagefilethumb`, `imagefilestd`, `imagefilezoom`, `imagedesc`, `imagedateadded`, `imagefiletinysize`, `imagefilethumbsize`, `imagefilestdsize`, `imagefilezoomsize`) VALUES(38, 19, '', 'sample_images/higher__70104.jpg', 1, 0, '', '', '', '', '', 1256533712, '', '', '', '');
INSERT INTO `%%PREFIX%%product_images` (`imageid`, `imageprodid`, `imageprodhash`, `imagefile`, `imageisthumb`, `imagesort`, `imagefiletiny`, `imagefilethumb`, `imagefilestd`, `imagefilezoom`, `imagedesc`, `imagedateadded`, `imagefiletinysize`, `imagefilethumbsize`, `imagefilestdsize`, `imagefilezoomsize`) VALUES(41, 18, '', 'sample_images/crumpler1__37065.jpg', 1, 0, '', '', '', '', '', 1256533712, '', '', '', '');
INSERT INTO `%%PREFIX%%product_images` (`imageid`, `imageprodid`, `imageprodhash`, `imagefile`, `imageisthumb`, `imagesort`, `imagefiletiny`, `imagefilethumb`, `imagefilestd`, `imagefilezoom`, `imagedesc`, `imagedateadded`, `imagefiletinysize`, `imagefilethumbsize`, `imagefilestdsize`, `imagefilezoomsize`) VALUES(42, 18, '', 'sample_images/crumpler2__94136.jpg', 0, 1, '', '', '', '', '', 1256533712, '', '', '', '');
INSERT INTO `%%PREFIX%%product_images` (`imageid`, `imageprodid`, `imageprodhash`, `imagefile`, `imageisthumb`, `imagesort`, `imagefiletiny`, `imagefilethumb`, `imagefilestd`, `imagefilezoom`, `imagedesc`, `imagedateadded`, `imagefiletinysize`, `imagefilethumbsize`, `imagefilestdsize`, `imagefilezoomsize`) VALUES(45, 16, '', 'sample_images/loginano__12692.jpg', 1, 0, '', '', '', '', '', 1256533712, '', '', '', '');
INSERT INTO `%%PREFIX%%product_images` (`imageid`, `imageprodid`, `imageprodhash`, `imagefile`, `imageisthumb`, `imagesort`, `imagefiletiny`, `imagefilethumb`, `imagefilestd`, `imagefilezoom`, `imagedesc`, `imagedateadded`, `imagefiletinysize`, `imagefilethumbsize`, `imagefilestdsize`, `imagefilezoomsize`) VALUES(48, 15, '', 'sample_images/wirelessm__74223.jpg', 1, 0, '', '', '', '', '', 1256533712, '', '', '', '');
INSERT INTO `%%PREFIX%%product_images` (`imageid`, `imageprodid`, `imageprodhash`, `imagefile`, `imageisthumb`, `imagesort`, `imagefiletiny`, `imagefilethumb`, `imagefilestd`, `imagefilezoom`, `imagedesc`, `imagedateadded`, `imagefiletinysize`, `imagefilethumbsize`, `imagefilestdsize`, `imagefilezoomsize`) VALUES(51, 14, '', 'sample_images/mighty__40520.jpg', 1, 0, '', '', '', '', '', 1256533712, '', '', '', '');
INSERT INTO `%%PREFIX%%product_images` (`imageid`, `imageprodid`, `imageprodhash`, `imagefile`, `imageisthumb`, `imagesort`, `imagefiletiny`, `imagefilethumb`, `imagefilestd`, `imagefilezoom`, `imagedesc`, `imagedateadded`, `imagefiletinysize`, `imagefilethumbsize`, `imagefilestdsize`, `imagefilezoomsize`) VALUES(54, 13, '', 'sample_images/ilife__42951.jpg', 1, 0, '', '', '', '', '', 1256533712, '', '', '', '');
INSERT INTO `%%PREFIX%%product_images` (`imageid`, `imageprodid`, `imageprodhash`, `imagefile`, `imageisthumb`, `imagesort`, `imagefiletiny`, `imagefilethumb`, `imagefilestd`, `imagefilezoom`, `imagedesc`, `imagedateadded`, `imagefiletinysize`, `imagefilethumbsize`, `imagefilestdsize`, `imagefilezoomsize`) VALUES(57, 12, '', 'sample_images/iwork__86080.jpg', 1, 0, '', '', '', '', '', 1256533712, '', '', '', '');
INSERT INTO `%%PREFIX%%product_images` (`imageid`, `imageprodid`, `imageprodhash`, `imagefile`, `imageisthumb`, `imagesort`, `imagefiletiny`, `imagefilethumb`, `imagefilestd`, `imagefilezoom`, `imagedesc`, `imagedateadded`, `imagefiletinysize`, `imagefilethumbsize`, `imagefilestdsize`, `imagefilezoomsize`) VALUES(60, 11, '', 'sample_images/office_media__14689.jpg', 1, 0, '', '', '', '', '', 1256533712, '', '', '', '');
INSERT INTO `%%PREFIX%%product_images` (`imageid`, `imageprodid`, `imageprodhash`, `imagefile`, `imageisthumb`, `imagesort`, `imagefiletiny`, `imagefilethumb`, `imagefilestd`, `imagefilezoom`, `imagedesc`, `imagedateadded`, `imagefiletinysize`, `imagefilethumbsize`, `imagefilestdsize`, `imagefilezoomsize`) VALUES(63, 10, '', 'sample_images/office_student__35938.jpg', 1, 0, '', '', '', '', '', 1256533712, '', '', '', '');
INSERT INTO `%%PREFIX%%product_images` (`imageid`, `imageprodid`, `imageprodhash`, `imagefile`, `imageisthumb`, `imagesort`, `imagefiletiny`, `imagefilethumb`, `imagefilestd`, `imagefilezoom`, `imagedesc`, `imagedateadded`, `imagefiletinysize`, `imagefilethumbsize`, `imagefilestdsize`, `imagefilezoomsize`) VALUES(66, 9, '', 'sample_images/eye250__84327.jpg', 1, 0, '', '', '', '', '', 1256533712, '', '', '', '');
INSERT INTO `%%PREFIX%%product_images` (`imageid`, `imageprodid`, `imageprodhash`, `imagefile`, `imageisthumb`, `imagesort`, `imagefiletiny`, `imagefilethumb`, `imagefilestd`, `imagefilezoom`, `imagedesc`, `imagedateadded`, `imagefiletinysize`, `imagefilethumbsize`, `imagefilestdsize`, `imagefilezoomsize`) VALUES(69, 8, '', 'sample_images/eyetvdtt__37033.jpg', 1, 0, '', '', '', '', '', 1256533712, '', '', '', '');
INSERT INTO `%%PREFIX%%product_images` (`imageid`, `imageprodid`, `imageprodhash`, `imagefile`, `imageisthumb`, `imagesort`, `imagefiletiny`, `imagefilethumb`, `imagefilestd`, `imagefilezoom`, `imagedesc`, `imagedateadded`, `imagefiletinysize`, `imagefilethumbsize`, `imagefilestdsize`, `imagefilezoomsize`) VALUES(72, 7, '', 'sample_images/mba1__75804.jpg', 1, 0, '', '', '', '', '', 1256533712, '', '', '', '');
INSERT INTO `%%PREFIX%%product_images` (`imageid`, `imageprodid`, `imageprodhash`, `imagefile`, `imageisthumb`, `imagesort`, `imagefiletiny`, `imagefilethumb`, `imagefilestd`, `imagefilezoom`, `imagedesc`, `imagedateadded`, `imagefiletinysize`, `imagefilethumbsize`, `imagefilestdsize`, `imagefilezoomsize`) VALUES(73, 7, '', 'sample_images/mba2__08931.jpg', 0, 1, '', '', '', '', '', 1256533712, '', '', '', '');
INSERT INTO `%%PREFIX%%product_images` (`imageid`, `imageprodid`, `imageprodhash`, `imagefile`, `imageisthumb`, `imagesort`, `imagefiletiny`, `imagefilethumb`, `imagefilestd`, `imagefilezoom`, `imagedesc`, `imagedateadded`, `imagefiletinysize`, `imagefilethumbsize`, `imagefilestdsize`, `imagefilezoomsize`) VALUES(74, 7, '', 'sample_images/mba3__58749.jpg', 0, 2, '', '', '', '', '', 1256533712, '', '', '', '');
INSERT INTO `%%PREFIX%%product_images` (`imageid`, `imageprodid`, `imageprodhash`, `imagefile`, `imageisthumb`, `imagesort`, `imagefiletiny`, `imagefilethumb`, `imagefilestd`, `imagefilezoom`, `imagedesc`, `imagedateadded`, `imagefiletinysize`, `imagefilethumbsize`, `imagefilestdsize`, `imagefilezoomsize`) VALUES(77, 6, '', 'sample_images/mbp1__99760.jpg', 1, 0, '', '', '', '', '', 1256533712, '', '', '', '');
INSERT INTO `%%PREFIX%%product_images` (`imageid`, `imageprodid`, `imageprodhash`, `imagefile`, `imageisthumb`, `imagesort`, `imagefiletiny`, `imagefilethumb`, `imagefilestd`, `imagefilezoom`, `imagedesc`, `imagedateadded`, `imagefiletinysize`, `imagefilethumbsize`, `imagefilestdsize`, `imagefilezoomsize`) VALUES(78, 6, '', 'sample_images/mbp2__50906.jpg', 0, 1, '', '', '', '', '', 1256533712, '', '', '', '');
INSERT INTO `%%PREFIX%%product_images` (`imageid`, `imageprodid`, `imageprodhash`, `imagefile`, `imageisthumb`, `imagesort`, `imagefiletiny`, `imagefilethumb`, `imagefilestd`, `imagefilezoom`, `imagedesc`, `imagedateadded`, `imagefiletinysize`, `imagefilethumbsize`, `imagefilestdsize`, `imagefilezoomsize`) VALUES(79, 6, '', 'sample_images/mbp3__81231.jpg', 0, 2, '', '', '', '', '', 1256533712, '', '', '', '');
INSERT INTO `%%PREFIX%%product_images` (`imageid`, `imageprodid`, `imageprodhash`, `imagefile`, `imageisthumb`, `imagesort`, `imagefiletiny`, `imagefilethumb`, `imagefilestd`, `imagefilezoom`, `imagedesc`, `imagedateadded`, `imagefiletinysize`, `imagefilethumbsize`, `imagefilestdsize`, `imagefilezoomsize`) VALUES(82, 5, '', 'sample_images/macbook__69047.jpg', 1, 0, '', '', '', '', '', 1256533712, '', '', '', '');
INSERT INTO `%%PREFIX%%product_images` (`imageid`, `imageprodid`, `imageprodhash`, `imagefile`, `imageisthumb`, `imagesort`, `imagefiletiny`, `imagefilethumb`, `imagefilestd`, `imagefilezoom`, `imagedesc`, `imagedateadded`, `imagefiletinysize`, `imagefilethumbsize`, `imagefilestdsize`, `imagefilezoomsize`) VALUES(83, 5, '', 'sample_images/macbook2__34944.jpg', 0, 1, '', '', '', '', '', 1256533712, '', '', '', '');
INSERT INTO `%%PREFIX%%product_images` (`imageid`, `imageprodid`, `imageprodhash`, `imagefile`, `imageisthumb`, `imagesort`, `imagefiletiny`, `imagefilethumb`, `imagefilestd`, `imagefilezoom`, `imagedesc`, `imagedateadded`, `imagefiletinysize`, `imagefilethumbsize`, `imagefilestdsize`, `imagefilezoomsize`) VALUES(84, 5, '', 'sample_images/macbook3__62330.jpg', 0, 2, '', '', '', '', '', 1256533712, '', '', '', '');
INSERT INTO `%%PREFIX%%product_images` (`imageid`, `imageprodid`, `imageprodhash`, `imagefile`, `imageisthumb`, `imagesort`, `imagefiletiny`, `imagefilethumb`, `imagefilestd`, `imagefilezoom`, `imagedesc`, `imagedateadded`, `imagefiletinysize`, `imagefilethumbsize`, `imagefilestdsize`, `imagefilezoomsize`) VALUES(87, 4, '', 'sample_images/touch1__19419.jpg', 1, 0, '', '', '', '', '', 1256533712, '', '', '', '');
INSERT INTO `%%PREFIX%%product_images` (`imageid`, `imageprodid`, `imageprodhash`, `imagefile`, `imageisthumb`, `imagesort`, `imagefiletiny`, `imagefilethumb`, `imagefilestd`, `imagefilezoom`, `imagedesc`, `imagedateadded`, `imagefiletinysize`, `imagefilethumbsize`, `imagefilestdsize`, `imagefilezoomsize`) VALUES(88, 4, '', 'sample_images/touch2__02925.jpg', 0, 1, '', '', '', '', '', 1256533712, '', '', '', '');
INSERT INTO `%%PREFIX%%product_images` (`imageid`, `imageprodid`, `imageprodhash`, `imagefile`, `imageisthumb`, `imagesort`, `imagefiletiny`, `imagefilethumb`, `imagefilestd`, `imagefilezoom`, `imagedesc`, `imagedateadded`, `imagefiletinysize`, `imagefilethumbsize`, `imagefilestdsize`, `imagefilezoomsize`) VALUES(93, 3, '', 'sample_images/product_white_classic__81585.jpg', 1, 0, '', '', '', '', '', 1256533712, '', '', '', '');
INSERT INTO `%%PREFIX%%product_images` (`imageid`, `imageprodid`, `imageprodhash`, `imagefile`, `imageisthumb`, `imagesort`, `imagefiletiny`, `imagefilethumb`, `imagefilestd`, `imagefilezoom`, `imagedesc`, `imagedateadded`, `imagefiletinysize`, `imagefilethumbsize`, `imagefilestdsize`, `imagefilezoomsize`) VALUES(102, 1, '', 'sample_images/shuffle_silver__52909.jpg', 1, 0, '', '', '', '', '', 1256533712, '', '', '', '');
INSERT INTO `%%PREFIX%%product_images` (`imageid`, `imageprodid`, `imageprodhash`, `imagefile`, `imageisthumb`, `imagesort`, `imagefiletiny`, `imagefilethumb`, `imagefilestd`, `imagefilezoom`, `imagedesc`, `imagedateadded`, `imagefiletinysize`, `imagefilethumbsize`, `imagefilestdsize`, `imagefilezoomsize`) VALUES(103, 1, '', 'sample_images/shuffle2__44095.jpg', 0, 1, '', '', '', '', '', 1256533712, '', '', '', '');
INSERT INTO `%%PREFIX%%product_images` (`imageid`, `imageprodid`, `imageprodhash`, `imagefile`, `imageisthumb`, `imagesort`, `imagefiletiny`, `imagefilethumb`, `imagefilestd`, `imagefilezoom`, `imagedesc`, `imagedateadded`, `imagefiletinysize`, `imagefilethumbsize`, `imagefilestdsize`, `imagefilezoomsize`) VALUES(104, 1, '', 'sample_images/shuffle3__06686.jpg', 0, 2, '', '', '', '', '', 1256533712, '', '', '', '');
INSERT INTO `%%PREFIX%%product_images` (`imageid`, `imageprodid`, `imageprodhash`, `imagefile`, `imageisthumb`, `imagesort`, `imagefiletiny`, `imagefilethumb`, `imagefilestd`, `imagefilezoom`, `imagedesc`, `imagedateadded`, `imagefiletinysize`, `imagefilethumbsize`, `imagefilestdsize`, `imagefilezoomsize`) VALUES(107, 2, '', 'sample_images/nano_black__99806.jpg', 1, 0, '', '', '', '', '', 1256533712, '', '', '', '');
INSERT INTO `%%PREFIX%%product_images` (`imageid`, `imageprodid`, `imageprodhash`, `imagefile`, `imageisthumb`, `imagesort`, `imagefiletiny`, `imagefilethumb`, `imagefilestd`, `imagefilezoom`, `imagedesc`, `imagedateadded`, `imagefiletinysize`, `imagefilethumbsize`, `imagefilestdsize`, `imagefilezoomsize`) VALUES(108, 2, '', 'sample_images/nano2__05699.jpg', 0, 1, '', '', '', '', '', 1256533712, '', '', '', '');
INSERT INTO `%%PREFIX%%product_images` (`imageid`, `imageprodid`, `imageprodhash`, `imagefile`, `imageisthumb`, `imagesort`, `imagefiletiny`, `imagefilethumb`, `imagefilestd`, `imagefilezoom`, `imagedesc`, `imagedateadded`, `imagefiletinysize`, `imagefilethumbsize`, `imagefilestdsize`, `imagefilezoomsize`) VALUES(109, 2, '', 'sample_images/nano3__36479.jpg', 0, 2, '', '', '', '', '', 1256533712, '', '', '', '');
INSERT INTO `%%PREFIX%%product_images` (`imageid`, `imageprodid`, `imageprodhash`, `imagefile`, `imageisthumb`, `imagesort`, `imagefiletiny`, `imagefilethumb`, `imagefilestd`, `imagefilezoom`, `imagedesc`, `imagedateadded`, `imagefiletinysize`, `imagefilethumbsize`, `imagefilestdsize`, `imagefilezoomsize`) VALUES(115, 17, '', 'sample_images/wireless_1_20070813new__42329.jpg', 1, 0, '', '', '', '', '', 1256533712, '', '', '', '');