<?php
$GLOBALS['ISC_CFG']['ProductName'] = 'Webshop - Versao 9.0 | 2012';
$GLOBALS['ISC_CFG']['ControlPanelTitle'] = "Painel Administrativo - hostmp Versao 9.0 | 2012";
$GLOBALS['ISC_CFG']['AdminCopyright'] = 'Sistema <a target="_blank" href="http://hostmp.net/">HOSTMP.NET</a> &copy; Versao 9.0 | 2012 - Ano Atual: '.date('Y').'';
$GLOBALS['ISC_CFG']['AdminLogo'] = '<img id="logo" src="images/logo.png" border="0" />';
$GLOBALS['ISC_CFG']['HelpRSS'] = '';
$GLOBALS['ISC_LANG']['PopularHelpArticles'] = "Top Artigos de Ajuda";
$GLOBALS['ISC_LANG']['ViewKnowledgeBase'] = 'Ver Base de Ajuda';
$GLOBALS['ISC_CFG']['ViewKnowledgeBaseLink'] = 'javascript:LaunchHelp("http://www.google.com.br/q=%query%");';
$GLOBALS['ISC_CFG']['SearchKnowledgeBaseUrl'] = 'http://www.google.com.br/q=%query%';
$GLOBALS['ISC_CFG']['DisableLicenseKeyField'] = true;
$GLOBALS['ISC_CFG']['DisableDatabaseDetailFields'] = true;
$GLOBALS['ISC_CFG']['DisableStoreUrlField'] = false;
$GLOBALS['ISC_CFG']['DisablePathFields'] = false;
$GLOBALS['ISC_CFG']['DisableLoggingSettingsTab'] = false;
$GLOBALS['ISC_CFG']['DisableProxyFields'] = false;
$GLOBALS['ISC_CFG']['DisableSystemInfo'] = false;
$GLOBALS['ISC_CFG']['DisableBackupSettings'] = false;
$GLOBALS['ISC_CFG']['HiddenStoreLogTypes'] = '';
$GLOBALS['ISC_LANG']['BadLKHInv'] = "Sua Licensa e Invalida! Por Favor Entre em Contato para uma Nova Licensa.";
$GLOBALS['ISC_LANG']['BadLKHExp'] = "Sua Licensa Venceu em %s. Entre em Contato para uma Nova Licensa.";
$GLOBALS['ISC_LANG']['ReachedUserLimitMsg'] = "Voce nao pode mais adicionar usuarios na loja pois o seu limite e de %s usuarios. Para adicionar mais entre em contato para <a href='http://cliquemania.com' target='_blank'>atualizar</a>.";
$GLOBALS['ISC_LANG']['ReachedProductLimitMsg'] = "Voce nao pode mais adicionar produtos pois o limite e de apenas %s produtos. Para adicionar mais voce precisar fazer uma <a href='http://cliquemania.com' target='_blank'>atualizacao</a>.";
$GLOBALS['ISC_CFG']['DisableSendStudioIntegration'] = true;
$GLOBALS['ISC_LANG']['MailSettings'] = 'Email Marketer Settings';
$GLOBALS['ISC_LANG']['MailIntegration'] = 'E-Marketer V6 Integration';
$GLOBALS['ISC_LANG']['APIDetails'] = "E-Marketer V6 API Details";
$GLOBALS['ISC_LANG']['MailXMLPath'] = 'Email Marketer XML Path';
$GLOBALS['ISC_LANG']['MailXMLPathHelp'] = "The path to E-Marketer V6\'s xml.php file which allows Loja Virtual V2010 to \'talk\' to E-Marketer V6 via the API. See the help tips above for details on where to find this.";
$GLOBALS['ISC_LANG']['MailXMLToken'] = 'EMail Marketer XML Token';
$GLOBALS['ISC_LANG']['MailUsername'] = 'Email Marketer Username';
$GLOBALS['ISC_LANG']['MailAPIInitFailed'] = 'The E-Marketer V6 XML token and/or username are incorrect. Double check them and try again.';
$GLOBALS['ISC_LANG']['MailAPIInitSuccess'] = 'The E-Marketer V6 API has been enabled. Click the \'E-Marketer V6 Integration\' tab below to configure email preferences for your store.';
$GLOBALS['ISC_LANG']['MailAPIIntegrationSuccess'] = 'Your E-Marketer V6 integration preferences have been updated.';
$GLOBALS['ISC_LANG']['CaptureNewsletterSubscribers'] = 'Capture Newsletter Subscribers';
$GLOBALS['ISC_LANG']['YesCaptureNewsletterSubscribers'] = 'Yes, use E-Marketer V6 to capture newsletter subscribers from my store';
$GLOBALS['ISC_LANG']['MailUsernameHelp'] = 'The username you use when logging into the E-Marketer V6 control panel. This should be the same username for the account where you copied the XML token from.';
$GLOBALS['ISC_LANG']['MailXMLTokenHelp'] = "The XML token assigned to your E-Marketer V6 account. See the help tips above for details on where to find this.";
$GLOBALS['ISC_LANG']['MailSettingsIntro'] = '<div class=\'AppNotice\'><img src=\'images/info.gif\' style=\'float:left; margin-right:5px; margin-bottom:30px\' /> <a style=\'color:#005FA3; font-weight:bold;\' href=http://www.google.com target=_blank>E-Marketer V6</a> is email marketing software that you can use to send newsletters, special offers and promotions via email. When integrated into your store, E-Marketer V6 can automatically capture the details of people who signup for your newsletter. It can also capture customer details as they\'re placing an order, such as their name, email address, order total, country, etc. You can then send targeted emails to your customers and even follow up automatically with time-sensitive autoresponder emails which you can create and schedule in E-Marketer V6.</div><br />To enable E-Marketer V6 integration in your store you need to follow a few simple steps, which are shown below:<ul><li>Purchase a copy of E-Marketer V6 and install it.</li><li>Login to E-Marketer V6 and click on the "User Accounts" link at the top of the page</li><li>Click "Edit" next to your account and go to the "User Permissions" tab</li><li>Tick the "Yes, allow this user to use the XML API" checkbox to enable XML API access for your account</li><li>Copy the "XML path", "XML token" values into their respective fields below</li><li>Enter the username that you use to login to your copy of E-Marketer V6 in the "Username" field below</li><li>If you don\'t see the XML API details in your copy of E-Marketer V6 then you need to upgrade to the latest version</li><li>Click the "Save" button in E-Marketer V6 to save your account preferences</li><li>Click the "Save" button below and you will then be able to configure your email preferences</li></ul><em>Please note: <strong>You must be running E-Marketer V6 5.0 or above to integrate into your store.</strong> To check which version of E-Marketer V6 you\'re running, login to your copy of E-Marketer V6, click the Tools menu and choose the System Information option. If you don\'t have this tab in your version then you need to upgrade before you can integrate E-Marketer V6 into your store.</em>';
$GLOBALS['ISC_LANG']['MailSettingsIntroDone'] = 'Update your E-Marketer V6 settings and integration preferences below.';
$GLOBALS['ISC_LANG']['InfoTipSendStudio'] = "For more help relating to integrating E-Marketer V6 into your store, please see <a href='javascript:void(0)' onclick='LaunchHelpCategory(108);'>this section</a> of the help guide.";
$GLOBALS['ISC_LANG']['CaptureNewsletterSubscribersHelp'] = 'Would you like E-Marketer V6 to automatically capture the details of people who subscribe to your newsletter from both the form on your web site and during the checkout process?<br /><br />If yes, tick this box and choose a mailing list where their email address will be saved to. Optionally, you can also choose a custom field where their first name should be saved to.';
$GLOBALS['ISC_LANG']['YesCaptureNewCustomers'] = 'Yes, use E-Marketer V6 to capture new customer details from my store';
$GLOBALS['ISC_LANG']['CaptureNewsletterOrdersHelp'] = 'Would you like E-Marketer V6 to automatically capture the details of people who place an order from your web site? If yes, tick this box and choose a mailing list where their email address will be added to. Optionally, you can also store their order details by choosing custom fields below.';
$GLOBALS['ISC_LANG']['EnterMailUsername'] = 'Please enter your E-Marketer V6 account username.';
$GLOBALS['ISC_LANG']['ShowProductUpdateOptions'] = 'Show Product Update Options';
$GLOBALS['ISC_LANG']['YesShowProductUpdateOptions'] = 'Yes, use E-Marketer V6 to let customers receive product updates via email';
$GLOBALS['ISC_LANG']['ShowProductUpdateOptionssHelp'] = 'Would you like customers to be able to sign up to receive product updates after they\\\'ve purchased from you? If yes, tick this box and you can choose which E-Marketer V6 mailing list they should be added to.';
$GLOBALS['ISC_LANG']['TheNameOfTheProductHelp'] = "If you choose this option, the customer will be shown a list of products in their order along with a checkbox next to each product after their order is placed. For each checkbox they tick, they will be added to a separate product-specific mailing list. You need to create the mailing lists in E-Marketer V6 first.<br /><br />For example, if your customer has ordered an iPod Nano and an iPhone, and they tick the boxes to receive updates to both products, they will be added to two separate mailing lists - one for the iPod Nano and one for the iPhone. In this case you should create two lists in E-Marketer V6 - one called &quot;iPod Nano&quot; and one called &quot;iPhone&quot;. The names of the lists must match the exact name of the product.";
$GLOBALS['ISC_LANG']['TheCategoryOfTheProductHelp'] = "If you choose this option, the customer will be shown a list of products in their order along with a checkbox next to each product after their order is placed. For each checkbox they tick, they will be added to a separate category-specific mailing list. You will need to create the mailing lists in E-Marketer V6 first.<br /><br />For example, if your customer has ordered an iPod Nano (whose category is MP3 Player) and an iPhone (whose category is Phones), and they tick the boxes to receive updates to both products, they will be added to two separate mailing lists - one for MP3 players and one for phones. In this case you should create two lists in E-Marketer V6 - one called &quot;MP3 Players&quot; and one called &quot;Phones&quot;. The names of the lists must match the exact name of the category.";
$GLOBALS['ISC_LANG']['TheBrandOfTheProductHelp'] = "If you choose this option, the customer will be shown a list of products in their order along with a checkbox next to each product after their order is placed. For each checkbox they tick, they will be added to a separate brand-specific mailing list. You need to create the mailing lists in E-Marketer V6 first.<br /><br />For example, if your customer has ordered an Apple iPod Nano and a Sony Cybershot digital camera, and they tick the boxes to receive updates to both products, they will be added to two separate mailing lists - one for Apple products and one for Sony products. In this case you should create two lists in E-Marketer V6 - one called &quot;Apple&quot; and one called &quot;Sony&quot;. The names of the lists must match the exact brand names used in your store.";
$GLOBALS['ISC_CFG']['MailLogo'] = 'images/iem_logo.gif';
$GLOBALS['ISC_CFG']['DisableKnowledgeManagerIntegration'] = true;
$GLOBALS['ISC_LANG']['KBSettings'] = 'Knowledge Manager';
$GLOBALS['ISC_LANG']['KBSettingsHeader'] = "Sistema de Ajuda";
$GLOBALS['ISC_LANG']['KBSettingsIntroDone'] = 'Update your Sistema de Ajuda settings and integration preferences below.';
$GLOBALS['ISC_LANG']['KBSettingsIntro'] = '<div class=\'AppNotice\'><img src=\'images/info.gif\' style=\'float:left; margin-right:5px; margin-bottom:30px\' /> <a style=\'color:#005FA3; font-weight:bold;\' href=http://www.google.com target=_blank>Sistema de Ajuda</a> is knowledge base &amp; FAQ software that you can use to provide your customers with answers to common questions about orders, shipping, returns, etc. Most customers want to learn about your store\'s policies, etc before they buy, and a knowledge base is a great way to give them answers to their questions. When integrated into your store, Sistema de Ajuda will look the same as your store and will show up as a link on your store\'s navigation menu.</div>To enable Sistema de Ajuda integration in your store you need to follow a few simple steps, which are shown below:<ul><li>Purchase a copy of Sistema de Ajuda and install it.</li><li>Login to Sistema de Ajuda and click on the "Settings" link at the top of the page</li><li>Under the "Site Settings" section, change the template to minhaloja</li><li>Paste this into the "Template Header URL" field: <strong>%s/top.php</strong></li><li>Paste this into the "Template Footer URL" field: <strong>%s/bottom.php</strong></li><li>Click the "Save" button in Sistema de Ajuda to update your settings</li><li>Click the "Website Content" tab above and choose the "Create a Web Page" link</li><li>Type a title for the page (such as "FAQ" or "Help") into the "Page Title" field</li><li>Choose the "Link to another website or document" page type</li><li>Enter the URL of where Sistema de Ajuda is installed (such as http://www.yoursite.com/kb) in the "Link" field</li><li>Click the "Save" button</li><li>View your store and when you click on the "FAQ" or "Help" page which you just created, your knowledge base will be shown</li><li>Optionally you can also integrate Sistema de Ajuda&#39;s <em>Active Response System</em> into your store by filling out the form below</li></ul>';
$GLOBALS['ISC_LANG']['KBDetails'] = 'Knowledge Manager Integration Details';
$GLOBALS['ISC_LANG']['KBPath'] = 'Knowledge Manager Path';
$GLOBALS['ISC_LANG']['KBPathHelp'] = 'The full URL to where your copy of Sistema de Ajuda is installed, such as http://www.yoursite.com/knowledgemanager. Do not include a trailing slash or index.php on the end of the URL.';
$GLOBALS['ISC_LANG']['KBContactFormIntegration'] = 'Contact Form Integration';
$GLOBALS['ISC_LANG']['YesKBContactFormIntegration'] = 'Yes, integrate Sistema de Ajuda&#39;s <em>Active Response System</em> into my contact form';
$GLOBALS['ISC_LANG']['KBContactFormIntegrationHelp'] = 'Do you want to integrate Sistema de Ajuda\\\'s <em>Active Response System</em> into any pages in your store that are setup as a contact form? If yes, tick this box and you can choose which page(s) to integrate it into.';
$GLOBALS['ISC_LANG']['IntegrateActiveResponseHelp'] = "Which web pages in your store do you want to integrate Sistema de Ajuda\'s <em>Active Response System</em> into? The pages listed here are the ones you\'ve created whose page type is \'<em>Allow people to send questions/comments via a contact form</em>\'.<br /><br />You can create another web page by choosing the \'Create a Web Page\' option from the Website Content tab above.";
$GLOBALS['ISC_LANG']['NoContactPagesForActiveKB'] = "Before you can integrate Sistema de Ajuda Active Response System you need to create at least one contact page. To create a contact page, click the 'Create a Web Page' link under the 'Website Content' tab above and choose the contact page option.";
$GLOBALS['ISC_LANG']['EnterActiveKBPath'] = 'Please enter the full URL to your copy of Sistema de Ajuda, such as http://www.yoursite.com/knowledgemanager';
$GLOBALS['ISC_LANG']['AKBSettingsSavedSuccessfully'] = 'Your Sistema de Ajuda settings have been saved successfully.';
$GLOBALS['ISC_LANG']['AKBSettingsNotSaved'] = 'Your Sistema de Ajuda settings couldn&#39;t be saved. Make sure your config/config.php file is writable and try again.';
$GLOBALS['ISC_LANG']['KBWhatIsActiveResponse'] = "What is Sistema de Ajuda Active Response System?";
$GLOBALS['ISC_CFG']['KBLogo'] = 'images/ikm_logo.gif';
$GLOBALS['ISC_CFG']['DisableAddons'] = false;
$GLOBALS['ISC_CFG']['DisableAddonDownloading'] = true;
$GLOBALS['ISC_CFG']['AddonXMLFile'] = '';
$GLOBALS['ISC_CFG']["AddonLicenseURL"] = "";
$GLOBALS['ISC_CFG']["AddonStreamURL"] = "";
$GLOBALS['ISC_CFG']['TemplateURL'] = "";
$GLOBALS['ISC_CFG']['TemplateInfoURL'] = "";
$GLOBALS['ISC_CFG']['TemplateVerifyURL'] = "";
$GLOBALS['ISC_CFG']['TemplateStreamURL'] = "";
$GLOBALS['ISC_CFG']['TemplateVersionURL'] = "";
$GLOBALS['ISC_CFG']["TemplatesOrderCustomURL"] = "http://hostmp.net";
$GLOBALS['ISC_CFG']['TemplateMarkup'] = 1.00;
$GLOBALS['ISC_CFG']['AllowTemplatePurchase'] = 0;
$GLOBALS['ISC_CFG']['DisableTemplateDownloading'] = 1;
$GLOBALS['ISC_CFG']['DisableSystemInfoEdition'] = false;
$GLOBALS['ISC_CFG']['SystemInfoEditionUpgradeLink'] = "http://hostmp.net";
$GLOBALS['ISC_CFG']['DisableVersionCheck'] = true;
$GLOBALS['ISC_LANG']['NewVersionAvailable'] = "";
$GLOBALS['ISC_LANG']['ConverterDeleteStoreMsg'] = "Delete everything in my Webshop Versao 9.0 store first";
$GLOBALS['ISC_LANG']['ConverterDeleteStoreHelp'] = "If you tick this option all orders, customers, products, etc (except your current admin user account) will be deleted from your Loja Virtual V2012 store *before* the import wizard starts.";
$GLOBALS['ISC_LANG']['ConverterConfirmDeleteStore'] = "Are you sure you want to delete everything from your Loja Virtual V2010 store before importing? Click OK to proceed with the import or Cancel if you\'ve changed your mind.";
$GLOBALS['ISC_LANG']['ConverterDeletingStore'] = "Removendo de sua Loja Virtual V2012 loja...";
$GLOBALS['ISC_LANG']['DeletingCurrentStoreStatusTitle'] = "Removendo Loja Virtual V2012 Conteudo";
$GLOBALS['ISC_LANG']['DeletingCurrentStoreStatusDesc'] = "O conteudo de Loja Virtual V2012 foi removido...";
$GLOBALS['ISC_CFG']['HideHelpLink'] = true;
$GLOBALS['ISC_LANG']['TrialExpiresInXDays'] = 'Seu periodo de teste expirra em %s dias. <a href="http://hostmp.net" target="_blank">Clique aqui para mais informacoes.</a>';
$GLOBALS['ISC_CFG']['EnableBuiltInGateway'] = true;
$GLOBALS['ISC_CFG']['BuiltInGateway'] = '';
$GLOBALS['ISC_CFG']['DisableGettingStarted'] = true;
$GLOBALS['ISC_CFG']['DisableVideoWalkthrough'] = true;
$GLOBALS['ISC_CFG']['VideoWalkthroughFeed'] = '';
?>